version: '3'
services:

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - ci_network
    user: root

  sonarqube:
    container_name: sonar
    image: sonarqube:latest
    ports:
      - "9000:9000"
      - "9092"
      # - "9092:9092"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_conf:/opt/sonarqube/conf
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - ci_network

  nexus:
    container_name: nexus
    image: sonatype/nexus3
    # image: sonatypecommunity/nexus3:3.74.0-java17   # for arm64 chips
    environment:
      - JAVA_OPTS="-Dnexus.repository.upload.maxSize=500MB"
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - ci_network
    # command: ["-n", "65536"] 

networks:
  ci_network:
    driver: bridge

volumes:
  jenkins_home:
  nexus_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_conf:
